app = "pet-bot"
primary_region = "gru"

[processes]
  app = "python main.py"

[[vm]]
  memory = "256mb"
  cpu_kind = "shared"
  cpus = 1

[env]
  TZ = "America/Sao_Paulo"

[mounts]
  source = "data"
  destination = "/app/data"